// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwIm-iThPnLmrKEwnVcvbSaFhXxQgzUY',
    appId: '1:254945361521:web:67686dc6c60fa2da4765d0',
    messagingSenderId: '254945361521',
    projectId: 'e-commerce-app-2001',
    authDomain: 'e-commerce-app-2001.firebaseapp.com',
    storageBucket: 'e-commerce-app-2001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_I2uMRx-vquJVAUSncjsSzksQK2Hn4ek',
    appId: '1:254945361521:android:6e9731a8e63a56ec4765d0',
    messagingSenderId: '254945361521',
    projectId: 'e-commerce-app-2001',
    storageBucket: 'e-commerce-app-2001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI673m8xb1J_GKz2aJ0thIAQskqniAn8E',
    appId: '1:254945361521:ios:bfd896bf46dee2b24765d0',
    messagingSenderId: '254945361521',
    projectId: 'e-commerce-app-2001',
    storageBucket: 'e-commerce-app-2001.appspot.com',
    iosBundleId: 'com.example.eCommerceApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI673m8xb1J_GKz2aJ0thIAQskqniAn8E',
    appId: '1:254945361521:ios:bfd896bf46dee2b24765d0',
    messagingSenderId: '254945361521',
    projectId: 'e-commerce-app-2001',
    storageBucket: 'e-commerce-app-2001.appspot.com',
    iosBundleId: 'com.example.eCommerceApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwIm-iThPnLmrKEwnVcvbSaFhXxQgzUY',
    appId: '1:254945361521:web:4ea0390e66c458894765d0',
    messagingSenderId: '254945361521',
    projectId: 'e-commerce-app-2001',
    authDomain: 'e-commerce-app-2001.firebaseapp.com',
    storageBucket: 'e-commerce-app-2001.appspot.com',
  );
}
